TeamNatron/ReleaseNotes-WebApp

Dockerfile
package.json
public/index.html
src/App.js
src/App.test.js
src/actions/articleActions.js
src/actions/authActions.js
src/actions/productActions.js
src/actions/productActions.test.js
src/components/auth/Login.jsx
src/components/product/Product.jsx
src/components/screen/LandingScreen.jsx
src/reducers/articleReducer.js
src/reducers/combinedReducers.js
src/reducers/initialStates.js
src/reducers/productsReducer.js
src/reducers/productsReducer.test.js

User can now log in.
Closes #44

Feature login

---

src/components/releaseEditor/Column.jsx
src/components/releaseEditor/ReleaseNote.jsx
src/components/releaseEditor/TitleTextField.jsx
src/components/screen/ReleaseEditorScreen.jsx
src/requests/productVersion.js
src/requests/release.js
src/requests/releaseNote.js

- User can now choose which ProductVersion this Release is affiliated with.
- Fetches release notes from db.
- Now possible to create new release from web.
- Added isPublic switch.
- Added validation for all "fields".  This is without feedback..

Feature add release

---

src/components/releaseEditor/Column.jsx
src/components/releaseEditor/TitleTextField.jsx
src/components/screen/ReleaseEditorScreen.jsx

Feedback created

---

src/components/releaseEditor/ReleaseEditor.jsx

- fixed validation being ran before component mounted.
- fixed missing keys in bottom toolbar.
- fixed productversion uncontrolled/controlled error

Bugfixing in the Release editor

---

src/components/screen/ReleaseEditorScreen.jsx
src/components/screen/ReleaseEditorScreen.test.jsx
src/components/shared/ResponseSnackbar.jsx
src/reducers/combinedReducers.js
src/slices/errorSlice.js
src/slices/releaseSlice.js
src/slices/releaseSlice.test.js

The only commit to really check out should be 
e262b87

Feature feedback on edit release

---

src/components/screen/ReleaseEditorScreen.jsx
src/components/screen/ReleaseEditorScreen.test.jsx
src/components/shared/ResponseSnackbar.jsx
src/reducers/combinedReducers.js
src/slices/errorSlice.js
src/slices/releaseSlice.js
src/slices/releaseSlice.test.js

Created a snackbar which is used to display feedback to the user. The snackbar can be used by passing props with error or success  messages.

Feature feedback on create release

---

src/components/releaseView/DenseReleaseNoteRow.jsx
src/components/releaseView/FullReleaseNote.jsx
src/components/releaseView/HtmlWrapper.jsx
src/components/releaseView/ReleaseView.jsx

Laga release leser

---

src/components/releaseView/DenseReleaseNoteRow.jsx
src/components/releaseView/FullReleaseNote.jsx
src/components/releaseView/ReleaseView.jsx
src/components/shared/ReleaseH1.jsx
src/components/shared/ReleaseH2.jsx

Improve release viewer styling AB#158

---

src/components/Routes.jsx
src/components/screen/ReleaseScreen.jsx
src/components/screen/ReleasesScreen.jsx

- Added routing for each Release.
- When routing to specific release, the correct release gets rendered.

Feature routing release

---

src/components/Navbar.jsx
src/components/releaseView/ReleaseView.jsx
src/utils/parser.js

Release now gets a nice and formatted date.

Feature release formatted date

---

src/components/releaseView/ReleaseView.jsx

this removal was necessary since dummy data always got displayed.

Removed data in default props of ReleaseView

---

src/App.js

REact app now uses url from docker-compose

---

src/components/screen/AdminScreen.jsx

Added default title
All release notes in admin panel that doesn't contain title, receives default title.

Bugfix ab#203

---

src/components/releaseNoteEditor/ReleaseNoteEditor.jsx

- Fikset feilen med "changed from controller/uncontrolled" der det manglet en default value.
- Noen hadde glemt å legge ved isPublic i objektet som ble sendt til server.

Default value for ready state set to false. AB#202

---

src/components/screen/AdminScreen.jsx
src/components/shared/AdminExpansionPanelBase.jsx
src/components/shared/AdminExpansionPanelRoute.jsx
src/components/shared/DeleteDialogButton.jsx
src/slices/releaseNoteSlice.js
src/slices/releaseSlice.js
src/utils/stateUtil.js

Laga en søppelkasse-knapp i expansion panela til release og release notes. Når den blir trykt får brukeren en dialog der dei må bekrefte at dei vil slette.

Sletting av releases og release notes

---

src/components/adminpanel/AzureDevopsView.jsx
src/components/screen/AdminScreen.jsx

Adminpanel now consists of two tabs, where one hosts all the regular administrative tasks, and the other will be hosting the new Azure Devops import tasks.

Feature adminpanel tabs

---

src/slices/authSlice.js
src/slices/authSlice.test.js

Oppdatert reducer til å håndtere oppdateringer med Azure Auth Info.
Opprettet tester til denne funksjonaliteten.

Feature send updated azure info

---

src/components/adminpanel/AzureDevOpsView.jsx
src/components/screen/AdminScreen.jsx
src/components/shared/AdminExpansionPanelBase.jsx
src/slices/azureSlice.js
src/slices/azureSlice.test.js

Created three new thunks.
- Fetch Azure Work Items of specified Release.
- Fetch Work item of specified Work items.
- Import all of this into a Release Note System Release with post request.
Implemented new thunks in UI
When import button for release is pressed, a series of requests
are sent to create a new release into Release Notes System.

Feature/import release AB#240

---

src/components/adminpanel/AzureDevOpsView.jsx
src/components/releaseNoteEditor/ReleaseNoteEditor.jsx
src/components/screen/AdminScreen.jsx
src/components/shared/AdminExpansionPanelBase.jsx
src/components/shared/GeneralSelector.jsx
src/slices/azureSlice.js
src/slices/productsSlice.js
src/slices/productsSlice.test.js

Opprettet en ny Selector for ProductVersion, denne trengs for å kunne lage ny release.

ProductVersionSelector i Azure Devops-panel AB#251

---

src/components/screen/AdminScreen.jsx

Flytta alle selectors ut av AdminScreen funksjonen. Kaffor? Fila blir lettere å lese. Også gitt selectorane `createSelector` behandling for bedre ytelse

Reselection

---

package-lock.json
package.json
src/components/adminpanel/EditProductForm.jsx
src/slices/productsSlice.js
src/slices/productsSlice.test.js

Her har det skjedd noen drastiske endringer for at kabelen skulle gå opp.
Nytt bibliotek implementert, Material-tables
https://material-table.com/#/
Full støtte for alle CRUD operasjoner, filterring, sortering, paging og søking.
Funksjoner som er lagt til:
- Mulighet for å opprette nye versjoner for et spesifikt produkt.
- Mulighet for å endre en versjon for et spesifikt produkt.

ProductVersion CRUD-panel AB#48

---

src/components/screen/LoginScreen.jsx
src/slices/authSlice.js

Login returns a promise which is used to determine if the user is going to get sent over to the adminscreen or not.

Routing on successful login

---

src/components/adminpanel/ChangePasswordForm.jsx

local checks on pw length

---

src/components/releaseView/ReleaseView.jsx

fixes [AB#258](https://dev.azure.com/ReleaseNoteSystem/399f705f-cd58-45f2-becb-f890cb50f774/_workitems/edit/258)

add length check on dense-notes

---

src/App.js
src/components/Footer.jsx

[AB#267](https://dev.azure.com/ReleaseNoteSystem/399f705f-cd58-45f2-becb-f890cb50f774/_workitems/edit/267)

less annoying footer

---

src/components/releaseEditor/Column.jsx

Min-height i taskList i Release Editor. Gjer det mulig å drag-n-drop uten å måtte bruke pinsett

add min-height

---

src/components/adminpanel/AzureDevOpsView.jsx
src/components/adminpanel/AzureMappingView.jsx
src/components/releaseEditor/Column.jsx
src/slices/authSlice.js
src/slices/azureSlice.js
src/slices/mappingSlice.js
src/utils/azureUtils.js

Denne PR vil inneholde alle features for front-end i User Story 289.
Foreløpig vil den kun eksistere som en draft-PR.

Mapping System Release Notes -> AzureDevOps Work items AB#289 AB#301

---

src/components/adminpanel/AzureDevOpsView.jsx
src/components/adminpanel/AzureMappingView.jsx
src/slices/mappingSlice.js

Det som finnes i denne PR er funksjonalitet for å hente inn alle eksiterende mappinger, som vises i en tabell (vist under). Her kan mange også editere hver enkelt rad med felt fra Work Items.

Mapping table for mapping ReleaseNotes to WorkItems in Azure AB#315 AB#317

---

src/components/adminpanel/EditProductForm.jsx
src/slices/productsSlice.js

- Created a new thunk for updating PV.
- Impemented new thunk in onUpdate of table.

Nå mulig å oppdatere productVersion AB#336

---

src/components/adminpanel/AzureMappingView.jsx
src/components/shared/GeneralSelector.jsx
src/slices/azureSlice.js
src/slices/azureSlice.test.js
src/slices/releaseSlice.js

- Fjernet noen dårlige props i `GeneralSelector.jsx`.
- Oppdatert Import Release til å sende råe WorkItems.
- Oppdatert Import Release til å bruke nytt endpoint.
- Mappings oppdateres når den skal, det vil si når nye alternativer til felt oppstår, blir tabellen oppdatert.
MERK** DENNE PR ER AVHENGIG AV [AB#327](https://dev.azure.com/ReleaseNoteSystem/399f705f-cd58-45f2-becb-f890cb50f774/_workitems/edit/327)**

Import Release oppdatert versjon AB#342
